In [1]:
import os
import clr
import random
import numpy as np
import pandas as pd
import faker as Faker
import matplotlib.pyplot as plt
from datetime import datetime, date

In [2]:
cwd = os.getcwd()  # Get the current working directory (cwd)
files = os.listdir(cwd)  # Get all the files in that directory
print("Files in %r: %s" % (cwd, files))

Files in 'C:\\Users\\grhan\\Desktop\\ADM\\Project\\Final_Project\\1. Data_preprocessing': ['.ipynb_checkpoints', 'Data_Preprocessing-Copy1.ipynb', 'Data_Preprocessing.ipynb', 'ml-100k', 'ml-100k.zip', 'New_User_Data.csv']

In [3]:
DATASET_LINK='http://files.grouplens.org/datasets/movielens/ml-100k.zip'

In [4]:
!wget -nc http://files.grouplens.org/datasets/movielens/ml-100k.zip
!unzip -n ml-100k.zip

File `ml-100k.zip' already there, will not retrieve.

Archive:  ml-100k.zip

In [5]:
overall_stats = pd.read_csv('ml-100k/u.info', header=None)
print("Details of users, items and ratings involved in the loaded movielens dataset: ",list(overall_stats[0]))

Details of users, items and ratings involved in the loaded movielens dataset:  ['943 users', '1682 items', '100000 ratings']

In [6]:
#Process the dataset for movies, users,ratings and genre
# Load each data set (users, movies, and ratings).
users_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
users = pd.read_csv(
    'ml-100k/u.user', sep='|', names=users_cols, encoding='latin-1')

ratings_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_csv(
    'ml-100k/u.data', sep='\t', names=ratings_cols, encoding='latin-1')

In [7]:
# The movies file contains a binary feature for each genre.
genre_cols = [
    "genre_unknown", "Action", "Adventure", "Animation", "Children", "Comedy",
    "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror",
    "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western",
]
movies_cols = [
    'movie_id', 'title', 'release_date', "video_release_date", "imdb_url"
] + genre_cols
movies = pd.read_csv(
    'ml-100k/u.item', sep='|', names=movies_cols, encoding='latin-1')

In [8]:
# Since the ids start at 1, we shift them to start at 0.
users["user_id"] = users["user_id"].apply(lambda x: str(x-1))
movies["movie_id"] = movies["movie_id"].apply(lambda x: str(x-1))
movies["year"] = movies['release_date'].apply(lambda x: str(x).split('-')[-1])
ratings["movie_id"] = ratings["movie_id"].apply(lambda x: str(x-1))
ratings["user_id"] = ratings["user_id"].apply(lambda x: str(x-1))
ratings["rating"] = ratings["rating"].apply(lambda x: float(x))

In [9]:
#Get all the genres for a movie
import numpy as np
genre_occurences = movies[genre_cols].sum().to_dict()

genres_encoded = {x: i for i, x in enumerate(genre_cols)}

def get_genres(movies, genres):
  def get_all_genres(gs):
    active = [str(genres_encoded[genre]) for genre, g in zip(genres, gs) if g==1]
    if len(active) == 0:
      return '0'
    return ','.join((active))
  movies['all_genres'] = [
      get_all_genres(gs) for gs in zip(*[movies[genre] for genre in genres])]

get_genres(movies, genre_cols)

In [10]:
movies

,movie_id,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,Animation,Children,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year,all_genres
0,0,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1995,"3,4,5"
1,1,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,1,0,0,1995,"1,2,16"
2,2,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1995,16
3,3,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1995,"1,5,8"
4,4,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,1,0,0,1995,"6,8,16"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1677,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1998,8
1678,1678,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,1,0,1,0,0,1998,"14,16"
1679,1679,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,1,0,0,0,0,1998,"8,14"
1680,1680,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1994,5
1681,1681,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1996,8

In [11]:
merged_dataset = ratings.merge(movies, on='movie_id').merge(users, on='user_id')

In [12]:
merged_dataset['user_id']=merged_dataset['user_id'].astype(int)
merged_dataset['movie_id']=merged_dataset['movie_id'].astype(int)

In [16]:
merged_dataset=merged_dataset.set_index(['user_id']).sort_index()

In [13]:
merged_dataset =merged_dataset.reset_index()

In [15]:
#merged_dataset.sort_values('user_id')

,user_id,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,...,Sci-Fi,Thriller,War,Western,year,all_genres,age,sex,occupation,zip_code
1722,0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,...,0,0,0,0,1996,"8,13",24,M,technician,85711
1643,0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,...,0,0,0,0,1986,"1,14",24,M,technician,85711
1642,0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,...,0,1,0,0,1996,"1,16",24,M,technician,85711
1641,0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,...,0,0,0,0,1994,"5,14",24,M,technician,85711
1640,0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,...,0,1,0,0,1996,"1,16",24,M,technician,85711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51818,942,720,5.0,888639660,Mallrats (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Mallrats%20(1...,0,0,...,0,0,0,0,1995,5,22,M,student,77841
51819,942,942,5.0,888639614,Killing Zoe (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Killing%20Zoe...,0,0,...,0,1,0,0,1994,16,22,M,student,77841
51820,942,823,4.0,875502483,"Great White Hype, The (1996)",03-May-1996,NaN,http://us.imdb.com/M/title-exact?Great%20White...,0,0,...,0,0,0,0,1996,5,22,M,student,77841
51811,942,184,2.0,888639370,Psycho (1960),01-Jan-1960,NaN,http://us.imdb.com/M/title-exact?Psycho%20(1960),0,0,...,0,1,0,0,1960,"11,14,16",22,M,student,77841
51728,942,233,3.0,888693184,Jaws (1975),01-Jan-1975,NaN,http://us.imdb.com/M/title-exact?Jaws%20(1975),0,1,...,0,0,0,0,1975,"1,11",22,M,student,77841

In [17]:
merged_dataset

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,Sci-Fi,Thriller,War,Western,year,all_genres,age,sex,occupation,zip_code
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,0,0,0,0,1996,"8,13",24,M,technician,85711
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,0,0,0,0,1986,"1,14",24,M,technician,85711
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,0,1,0,0,1996,"1,16",24,M,technician,85711
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,0,0,0,0,1994,"5,14",24,M,technician,85711
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,0,1,0,0,1996,"1,16",24,M,technician,85711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,720,5.0,888639660,Mallrats (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Mallrats%20(1...,0,0,0,...,0,0,0,0,1995,5,22,M,student,77841
942,942,5.0,888639614,Killing Zoe (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?Killing%20Zoe...,0,0,0,...,0,1,0,0,1994,16,22,M,student,77841
942,823,4.0,875502483,"Great White Hype, The (1996)",03-May-1996,NaN,http://us.imdb.com/M/title-exact?Great%20White...,0,0,0,...,0,0,0,0,1996,5,22,M,student,77841
942,184,2.0,888639370,Psycho (1960),01-Jan-1960,NaN,http://us.imdb.com/M/title-exact?Psycho%20(1960),0,0,0,...,0,1,0,0,1960,"11,14,16",22,M,student,77841
942,233,3.0,888693184,Jaws (1975),01-Jan-1975,NaN,http://us.imdb.com/M/title-exact?Jaws%20(1975),0,1,0,...,0,0,0,0,1975,"1,11",22,M,student,77841

In [18]:
# Get the like and dislike movie list
merged_dataset['movie_liklihood'] = np.where(merged_dataset['rating'] >=3, 'like','dislike')
#merged_dataset['movie_name'] = merged_dataset['title'].str[:-6]

In [19]:
merged_dataset.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,Thriller,War,Western,year,all_genres,age,sex,occupation,zip_code,movie_liklihood
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,0,0,0,1996,"8,13",24,M,technician,85711,like
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,0,0,0,1986,"1,14",24,M,technician,85711,like
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,1,0,0,1996,"1,16",24,M,technician,85711,like
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,0,0,0,1994,"5,14",24,M,technician,85711,like
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,1,0,0,1996,"1,16",24,M,technician,85711,like

In [20]:
df = merged_dataset

In [21]:
from faker import Faker

faker = Faker()

arr1 = []

for x in df.index:
    arr1.append(faker.date_between_dates(date_start=datetime(2019,1,1), date_end=datetime(2019,12,31)))

In [22]:
df['Subscription_StartDate'] = arr1

In [23]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,War,Western,year,all_genres,age,sex,occupation,zip_code,movie_liklihood,Subscription_StartDate
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,0,0,1996,"8,13",24,M,technician,85711,like,2019-08-14
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,0,0,1986,"1,14",24,M,technician,85711,like,2019-11-07
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,0,0,1996,"1,16",24,M,technician,85711,like,2019-05-03
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,0,0,1994,"5,14",24,M,technician,85711,like,2019-09-19
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,0,0,1996,"1,16",24,M,technician,85711,like,2019-01-06

In [24]:
arr2 = []

for x in df.index:
    arr2.append(faker.date_between_dates(date_start=datetime(2021,1,1), date_end=datetime(2021,12,31)))

In [25]:
df['Subscription_EndDate'] = arr2

In [26]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,Western,year,all_genres,age,sex,occupation,zip_code,movie_liklihood,Subscription_StartDate,Subscription_EndDate
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,0,1996,"8,13",24,M,technician,85711,like,2019-08-14,2021-02-26
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,0,1986,"1,14",24,M,technician,85711,like,2019-11-07,2021-09-22
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,0,1996,"1,16",24,M,technician,85711,like,2019-05-03,2021-06-18
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,0,1994,"5,14",24,M,technician,85711,like,2019-09-19,2021-09-05
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,0,1996,"1,16",24,M,technician,85711,like,2019-01-06,2021-10-06

In [27]:
df['Subscription_Status'] = df['Subscription_EndDate']
string_input_with_date = date(2021,5,1)

print(string_input_with_date)

df['Subscription_Status'] = df['Subscription_Status'].apply(lambda x :'Subscribed' if x > string_input_with_date else 'Unsubscribed')

2021-05-01

In [28]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,year,all_genres,age,sex,occupation,zip_code,movie_liklihood,Subscription_StartDate,Subscription_EndDate,Subscription_Status
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,1996,"8,13",24,M,technician,85711,like,2019-08-14,2021-02-26,Unsubscribed
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,1986,"1,14",24,M,technician,85711,like,2019-11-07,2021-09-22,Subscribed
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,1996,"1,16",24,M,technician,85711,like,2019-05-03,2021-06-18,Subscribed
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,1994,"5,14",24,M,technician,85711,like,2019-09-19,2021-09-05,Subscribed
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,1996,"1,16",24,M,technician,85711,like,2019-01-06,2021-10-06,Subscribed

In [29]:
arr3 = []

for x in df.index:
    arr3.append(faker.pybool())

In [30]:
df['Coupon_Used?'] = arr3

In [31]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,all_genres,age,sex,occupation,zip_code,movie_liklihood,Subscription_StartDate,Subscription_EndDate,Subscription_Status,Coupon_Used?
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,"8,13",24,M,technician,85711,like,2019-08-14,2021-02-26,Unsubscribed,True
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,"1,14",24,M,technician,85711,like,2019-11-07,2021-09-22,Subscribed,True
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,"1,16",24,M,technician,85711,like,2019-05-03,2021-06-18,Subscribed,True
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,"5,14",24,M,technician,85711,like,2019-09-19,2021-09-05,Subscribed,False
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,"1,16",24,M,technician,85711,like,2019-01-06,2021-10-06,Subscribed,False

In [32]:
df['Coupon_Used?'] = df['Coupon_Used?'].apply(lambda x :'Yes' if x == True else 'No')

In [33]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,all_genres,age,sex,occupation,zip_code,movie_liklihood,Subscription_StartDate,Subscription_EndDate,Subscription_Status,Coupon_Used?
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,"8,13",24,M,technician,85711,like,2019-08-14,2021-02-26,Unsubscribed,Yes
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,"1,14",24,M,technician,85711,like,2019-11-07,2021-09-22,Subscribed,Yes
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,"1,16",24,M,technician,85711,like,2019-05-03,2021-06-18,Subscribed,Yes
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,"5,14",24,M,technician,85711,like,2019-09-19,2021-09-05,Subscribed,No
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,"1,16",24,M,technician,85711,like,2019-01-06,2021-10-06,Subscribed,No

In [34]:
import random
arr4 = []
for x in df.index:
    arr4 .append(random.randint(2000,40000))

In [35]:
df['Monthly Income'] = arr4

In [36]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,age,sex,occupation,zip_code,movie_liklihood,Subscription_StartDate,Subscription_EndDate,Subscription_Status,Coupon_Used?,Monthly Income
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,24,M,technician,85711,like,2019-08-14,2021-02-26,Unsubscribed,Yes,2117
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,24,M,technician,85711,like,2019-11-07,2021-09-22,Subscribed,Yes,18654
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,24,M,technician,85711,like,2019-05-03,2021-06-18,Subscribed,Yes,4395
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,24,M,technician,85711,like,2019-09-19,2021-09-05,Subscribed,No,37259
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,24,M,technician,85711,like,2019-01-06,2021-10-06,Subscribed,No,15602

In [37]:
StartDate_Year = []
StartDate_Month = []

for x in df['Subscription_StartDate'] :
    StartDate_Year.append(x.year)
    StartDate_Month.append(x.month)

In [38]:
df['StartDate_Year'] = StartDate_Year
df['StartDate_Month'] = StartDate_Month

In [39]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,occupation,zip_code,movie_liklihood,Subscription_StartDate,Subscription_EndDate,Subscription_Status,Coupon_Used?,Monthly Income,StartDate_Year,StartDate_Month
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,technician,85711,like,2019-08-14,2021-02-26,Unsubscribed,Yes,2117,2019,8
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,technician,85711,like,2019-11-07,2021-09-22,Subscribed,Yes,18654,2019,11
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,technician,85711,like,2019-05-03,2021-06-18,Subscribed,Yes,4395,2019,5
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,technician,85711,like,2019-09-19,2021-09-05,Subscribed,No,37259,2019,9
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,technician,85711,like,2019-01-06,2021-10-06,Subscribed,No,15602,2019,1

In [40]:
EndDate_Year = []
EndDate_Month = []

for x in df['Subscription_EndDate'] :
    EndDate_Year.append(x.year)
    EndDate_Month.append(x.month)

In [41]:
df['EndDate_Year'] = EndDate_Year
df['EndDate_Month'] = EndDate_Month

In [42]:
df['Total_Months_Subscription'] = (df['EndDate_Year'] - df['StartDate_Year']) * 12 + (df['EndDate_Month'] - df['StartDate_Month'])

In [43]:
df['Subscription_Cost'] = df['Total_Months_Subscription'] * 10

In [44]:
df.head()

,movie_id,rating,timestamp,title,release_date,video_release_date,imdb_url,genre_unknown,Action,Adventure,...,Subscription_EndDate,Subscription_Status,Coupon_Used?,Monthly Income,StartDate_Year,StartDate_Month,EndDate_Year,EndDate_Month,Total_Months_Subscription,Subscription_Cost
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,875071484,Lone Star (1996),21-Jun-1996,NaN,http://us.imdb.com/M/title-exact?Lone%20Star%2...,0,0,0,...,2021-02-26,Unsubscribed,Yes,2117,2019,8,2021,2,18,180
0,160,4.0,875072303,Top Gun (1986),01-Jan-1986,NaN,http://us.imdb.com/M/title-exact?Top%20Gun%20(...,0,1,0,...,2021-09-22,Subscribed,Yes,18654,2019,11,2021,9,22,220
0,146,3.0,875240993,"Long Kiss Goodnight, The (1996)",05-Oct-1996,NaN,http://us.imdb.com/M/title-exact?Long%20Kiss%2...,0,1,0,...,2021-06-18,Subscribed,Yes,4395,2019,5,2021,6,25,250
0,48,3.0,878542478,I.Q. (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?I.Q.%20(1994),0,0,0,...,2021-09-05,Subscribed,No,37259,2019,9,2021,9,24,240
0,127,4.0,875072573,Supercop (1992),26-Jul-1996,NaN,http://us.imdb.com/M/title-exact?Police%20Stor...,0,1,0,...,2021-10-06,Subscribed,No,15602,2019,1,2021,10,33,330

In [45]:
df = df.drop(['timestamp','release_date','video_release_date','imdb_url','year','zip_code'],axis = 1)

In [46]:
df.head()

,movie_id,rating,title,genre_unknown,Action,Adventure,Animation,Children,Comedy,Crime,...,Subscription_EndDate,Subscription_Status,Coupon_Used?,Monthly Income,StartDate_Year,StartDate_Month,EndDate_Year,EndDate_Month,Total_Months_Subscription,Subscription_Cost
user_id,,,,,,,,,,,,,,,,,,,,,
0,123,5.0,Lone Star (1996),0,0,0,0,0,0,0,...,2021-02-26,Unsubscribed,Yes,2117,2019,8,2021,2,18,180
0,160,4.0,Top Gun (1986),0,1,0,0,0,0,0,...,2021-09-22,Subscribed,Yes,18654,2019,11,2021,9,22,220
0,146,3.0,"Long Kiss Goodnight, The (1996)",0,1,0,0,0,0,0,...,2021-06-18,Subscribed,Yes,4395,2019,5,2021,6,25,250
0,48,3.0,I.Q. (1994),0,0,0,0,0,1,0,...,2021-09-05,Subscribed,No,37259,2019,9,2021,9,24,240
0,127,4.0,Supercop (1992),0,1,0,0,0,0,0,...,2021-10-06,Subscribed,No,15602,2019,1,2021,10,33,330

In [48]:
df.to_csv("User_Data.csv")